name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Vault
      run: |
        docker run -d --name vault \
        -e VAULT_DEV_ROOT_TOKEN_ID=root-token \
        -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200 \
        -e SKIP_SETCAP=true \
        -p 8200:8200 hashicorp/vault:1.17.0

    - name: Start PostgreSQL
      run: |
        docker run -d --name postgres \
        -e POSTGRES_DB=reviews_db \
        -e POSTGRES_USER=postgres \
        -e POSTGRES_PASSWORD=postgres123 \
        -p 5432:5432 postgres:15

    - name: Start Zookeeper
      run: |
        docker run -d --name zookeeper \
        -e ZOOKEEPER_CLIENT_PORT=2181 \
        -e ZOOKEEPER_TICK_TIME=2000 \
        confluentinc/cp-zookeeper:7.4.0

    - name: Start Kafka
      run: |
        docker run -d --name kafka \
        --link zookeeper:zookeeper \
        -e KAFKA_BROKER_ID=1 \
        -e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
        -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 \
        -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
        -p 9092:9092 confluentinc/cp-kafka:7.4.0

    - name: Init Vault secrets
      run: |
        sleep 5
        docker run --rm \
        --link vault:vault \
        -e VAULT_ADDR=http://vault:8200 \
        -e VAULT_TOKEN=root-token \
        -e SKIP_SETCAP=true \
        hashicorp/vault:1.17.0 \
        vault kv put secret/postgres db=reviews_db user=postgres password=postgres123 host=db port=5432

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/amazon-reviews-ml-lab4:latest

    - name: Run consumer
      run: |
        docker run -d --name consumer \
        --link vault:vault \
        --link postgres:db \
        --link kafka:kafka \
        -e VAULT_ADDR=http://vault:8200 \
        -e VAULT_TOKEN=root-token \
        -e KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
        ${{ secrets.DOCKER_USERNAME }}/amazon-reviews-ml-lab4:latest \
        python src/consumer.py

    - name: Run app container
      run: |
        docker run -d --name test-contai